Feature/av2 766/update chat api calls to new graphql apis
intersective/practera-app-v2 pull request #1000
Opened 2020-10-15 15:13 UTC by sasangachathumal

Jira story - https://intersective.atlassian.net/browse/AV2-766

2020-10-16 01:14 UTC, Barry-Chen-Intersective requested changes
@sasangachathumal , should call with correct data failed

2020-10-22 07:21 UTC, shawnm0705 requested changes

2020-10-22 07:21 UTC, shawnm0705 commented on src/app/chat/chat-room/chat-room.component.ts
> +        receivedMessage.fileObject = JSON.parse(receivedMessage.file);
better to check if it is a string, if so, JSON.parse()

2020-10-22 07:21 UTC, shawnm0705 commented on src/app/chat/chat.service.ts
> +    result.forEach(chat => {
Since the attributes are exactly the same, we don't need to re-assign it. 
GraphQL will make sure we get what we asked for

2020-10-22 07:21 UTC, shawnm0705 commented on src/app/chat/chat.service.ts
>    markAsSeen: 'api/v2/message/chat/edit_message'
Let's remove all those since we are not using them anymore

2020-10-23 00:09 UTC, shawnm0705 approved these changes

2020-10-23 00:23 UTC, Barry-Chen-Intersective approved these changes

2020-10-23 00:24 UTC, merged